id: ac437f0991164ab1a9b948846162a55b
initial_creation_type: ocr
source_metadata:
  volumes:
    75f4cfe0153c4f729367c13c8f82e2ec:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་རྣམ་པར་སྣང་མཛད་ཀྱི་མངོན་པར་རྟོགས་པ།
      total_pages: 1586
      volume_number: 24
